// List of US states for dropdown
const List<String> usStates = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
];

// Certification options
const List<String> cpaCertificationOptions = [
  'CPA',
  'EA',
  'CFP',
  'CMA',
  'CIA',
  'CGMA',
  'ChFC',
  'PFS',
  'Other',
];

// Specialty options
const List<String> cpaSpecialtyOptions = [
  'Individual Income Tax',
  'Small Business Tax',
  'Corporate Tax',
  'Partnership & LLC Tax',
  'Multi-State Taxation',
  'International Tax',
  'Trusts & Estates',
  'CFO Services',
  'Cryptocurrency Taxation',
  'Sales & Use Tax',
  'Payroll Tax Compliance',
  'Tax Strategy & Planning',
  'Bookkeeping & Accounting',
  'Audit & Assurance',
  'Financial Planning',
  'Estate Planning',
  'Business Valuation',
  'IRS Representation',
  'Non-Profit Accounting',
];

const List<String> cpaServices = [
  'Tax Preparation and Filing',
  'Tax Planning and Strategy',
  'Bookkeeping and Accounting',
  'CFO Services',
  'Financial Reporting/Valuation Services',
  'Corporate and Business Services',
  'Payroll and Employment Taxes',
  'Audit and Assurance',
  'International Tax Services',
  'Compliance and Regulatory',
  'Estate and Trust Tax Services',
  'Forensic Accounting',
  'Other',
];

const String personalTransactionType = "Personal";
const String businessTransactionType = "Business";

const List<String> transactionTypesList = [
  personalTransactionType,
  businessTransactionType,
];
