CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpa_id bigint NOT NULL,
    user_id bigint NOT NULL,
    title text NOT NULL,
    description text NULL,
    amount numeric NOT NULL,
    status text NOT NULL DEFAULT 'pending'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    start_date timestamp with time zone NULL,
    due_date timestamp with time zone NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_cpa_id_fkey FOREIGN KEY (cpa_id) REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);
