-- Drop table if it exists (since user mentioned they deleted it, but good safety)
DROP TABLE IF EXISTS public.orders;

-- Create the orders table
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpa_id bigint NOT NULL,
    user_id bigint NOT NULL,
    title text NOT NULL,
    description text NULL,
    amount numeric NOT NULL,
    status text NOT NULL DEFAULT 'pending'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    start_date timestamp with time zone NULL,
    due_date timestamp with time zone NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_cpa_id_fkey FOREIGN KEY (cpa_id) REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);

-- Enable Row Level Security
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own orders
CREATE POLICY "Users can view their own orders"
ON public.orders FOR SELECT
USING (
  auth.uid() IN (SELECT auth_id FROM public.users WHERE id = user_id)
);

-- Policy: CPAs can view orders assigned to them
CREATE POLICY "CPAs can view assigned orders"
ON public.orders FOR SELECT
USING (
  auth.uid() IN (SELECT auth_id FROM public.users WHERE id = cpa_id)
);

-- Policy: Users and CPAs can insert orders
-- (Assuming both can create, or restrict as needed. This allows both if they are involved in the order)
CREATE POLICY "Users and CPAs can insert orders"
ON public.orders FOR INSERT
WITH CHECK (
  auth.uid() IN (SELECT auth_id FROM public.users WHERE id = user_id)
  OR
  auth.uid() IN (SELECT auth_id FROM public.users WHERE id = cpa_id)
);

-- Policy: Users and CPAs can update their orders
CREATE POLICY "Users and CPAs can update their orders"
ON public.orders FOR UPDATE
USING (
  auth.uid() IN (SELECT auth_id FROM public.users WHERE id = user_id)
  OR
  auth.uid() IN (SELECT auth_id FROM public.users WHERE id = cpa_id)
);
