-- Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint references public.chats(id) on delete cascade not null,
  sender_id bigint not null,
  content text not null,
  type text check (type in ('text', 'image', 'file')) default 'text',
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;

-- IMPORTANT: RLS Policies
-- The application uses `int` or `bigint` for user IDs (e.g. sender_id), but Supabase Auth `auth.uid()` returns a UUID.
-- You cannot directly compare `sender_id = auth.uid()`.
-- You need a way to map the authenticated UUID to your integer User ID.
-- Usually this involves a lookup on a `users` or `profiles` table where `uuid_col = auth.uid()`.

-- Example Policy (COMMENTED OUT - ENABLE AFTER ADAPTING TO YOUR SCHEMA):

/*
create policy "Users can view messages in chats they belong to"
  on public.messages for select
  using (
    exists (
      select 1 from public.chats
      where id = messages.chat_id
      and (
          -- Replace `get_current_user_id()` with a function or subquery that gets the int ID from auth.uid()
          sender_id = (select id from public.users where uuid = auth.uid()) 
          or 
          receiver_id = (select id from public.users where uuid = auth.uid())
      )
    )
  );

create policy "Users can insert messages into chats they belong to"
  on public.messages for insert
  with check (
    exists (
      select 1 from public.chats
      where id = chat_id
      and (
          sender_id = (select id from public.users where uuid = auth.uid())
          or 
          receiver_id = (select id from public.users where uuid = auth.uid())
      )
    )
  );
*/
